format = """
[](#5e81ac)\
$os$username[@](bg:#5e81ac fg:#2e3440)$hostname\
[](bg:#81a1c1 fg:#5e81ac)\
$directory\
[](bg:#88c0d0 fg:#81a1c1)\
$git_branch$git_commit\
$git_state\
$git_status\
[](bg:#8fbcbb fg:#88c0d0)\
$package\
[](bg:#8fbcbb fg:#88c0d0)\
$c\
$cmake\
$golang\
$guix_shell\
$haskell\
$haxe\
$java\
$julia\
$kotlin\
$gradle\
$lua$nim\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python$\
quarto\
$raku\
$rlang\
$rust\
$swift\
$typst\
$vlang\
$zig\
[](bg:#d9dee9 fg:#8fbcbb)\
$cmd_duration\
[](fg:#d9dee9)\
$line_break\
$character
"""

add_newline = false

# EXCLUDED $
# ==========
# to add later if I need them lmao
# localip, shlvl, singularity, kubernetes
# vcsh, fossil_branch, fossil_branch_metrics, hg_branch, pijul_channel, docker_context
# buf, nix_shell, conda, meson, spack
# memory_usage
# aws, gcloud, openstack, azure
# direnv, env_var, crytal, custom, sudo
# jobs, status, container, shell

# GIT
# ===

[git_branch]
format = "[ $symbol$branch$remote_name(:$remote_branch) ]($style)"
symbol = "󰘬 "
style = "fg:#2e3440 bg:#88c0d0"

[git_commit]
tag_disabled = false
format = '[\($hash$tag\)]($style)'
style = "fg:#2e3440 bg:#88c0d0"

[git_state]
style = "fg:#2e3440 bg:#88c0d0"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
style = "fg:#2e3440 bg:#88c0d0"

# LANGUAGES
# =========

[package]
symbol = " "
style = "fg:#2e3440 bg:#8fbcbb"
format ='[ $symbol$version]($style)'

[c]
symbol = ' '
format = '[$symbol($version(-$name) )]($style)'
style = "fg:#2e3440 bg:#8fbcbb"

[lua]
symbol = '󰢱 '
format = '[ $symbol($version )]($style)'
style = "fg:#2e3440 bg:#8fbcbb"

[python]
symbol = '󰌠 '
format = "[ $symbol($version )$virtualenv]($style)"
style = "fg:#2e3440 bg:#8fbcbb"
pyenv_version_name = true
pyenv_prefix = "pyenv "

[rust]
symbol = ' '
format = "[ $symbol($version )]($style)"
style = "fg:#2e3440 bg:#8fbcbb"
version_format = 'v${raw}'
# MISC
# ====

[hostname]
ssh_only = false
style = "fg:#2e3440 bg:#5e81ac"
format = "[$ssh_symbol$hostname ]($style)"
ssh_symbol = " "

[os]
style = "fg:#2e3440 bg:#5e81ac"
disabled = false

[os.symbols]
Arch = ' '
Macos = ' '

[shell]
disabled = false

[username]
show_always = true
format = '[$user]($style)'
style_user = "fg:#2e3440 bg:#5e81ac"

[directory]
style = "fg:#2e3440 bg:#81a1c1"
read_only = " "
format = "[ 󰉋 $path ]($style)[$read_only]($read_only_style)"
read_only_style = "fg:#2e3440 bold bg:#81a1c1"

[sudo]
disabled = false
symbol = " "
style = "fg:#2e3440 bg:#d9dee9"
format = "[ $symbol]($style)"

[cmd_duration]
format = "[ 󰔚 $duration ]($style)"
style = "fg:#2e3440 bg:#d9dee9"

[character]
success_symbol = "[ 󱞩](bold green)"
error_symbol = "[ 󱞩](bold red)"
vimcmd_symbol = "[  󱞩](bold green)"
